### ISSUE TITLE
Bug: money drop missing configured head

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#155]
It would be awesome to be able to gift a BagOfGold to a player! Something like
> /mh give money amount

command, which would give me the ITEM or SKULL reward, which I could then drop to the player. Or maybe put it in a chest. So someone with appropriate permission (for example)
> mobhunting.giverewards

would be able to handle a reward without redemption, but when the player picked it up or took it from the chest, it would be redeemed. Just thinking out loud...

**Comment by Rocologo** [comment]
Thank you for making a ticket on this :-)

This will be easy to make. I'm currently investigation if I can save the value of the "bag of gold" on the item, so it can have a value. If I cant make this I will make "simple" solution for you. 

You just have to be patient because I dont have much development time these days and I need time to fight bugs too. :-)

**Comment by Rocologo** [comment]
I think the commands should be:

Admin command (permission mobhunting.money.give)
/mh money give playername amount 
- to give the player a bag of gold in his inventory. **Question** is if the money should be added to an existing bag or as a new bag. The money will be take from the "server" and not the player who executes the command.

/mh money take playername amount 
- to take some of the players money from his inventory. If amount is bigger or equal to the money in his inventory, the bag will be removed. The money will be given to the server and not the player who executes the command.

Admin command: (permission mobhunting.money.balance)
/mh money player 
- to show the value of the players total back of gold in the player inventory.

Admin command:
/mh money drop amount
- to drop some money in front of you. **Question** is if the money should be take from the player who executes the command or the server?

Sign to convert the "bag of gold" to the players acount. The sign must be placed on a chest. Left click to sell, Right click  to buy
Line1: [MH SHOP] 
Line2: <owner>|<Admin>
Line3: SELL|BUY
Line4: ALL|<number>

Line 1: Is a TAG so the plugin can recognize the "Shop sign"
Line 2: If the line is owner the owner will get the money/bag of gold, but not more that the player has on his account/bag of gold. I havnt thought this through yet. Im not sure if it is a god idea or if it only can be an Admin sign.
Line 3: Tells if the sign can be used for trading both way. Left click to SELL, Right click to Buy
Line 4: could be ALL or a number, if ALL all "bag of gold" or "money" will be converted, and account will be updated.

Player commands (permission: mobhunt.money.sell)
/mh money sell amount
- to convert bags of gold in the players inventory to money on the players account. Can be used instead of the sign.

Player commands (permission: mobhunt.money.buyl)
/mh money buy amount
- to convert money in the players account to bags of gold in his inventory. Can be used instead of the sign.

Any more ideas? 

This will take a lot of time to make all these features....

**Comment by SlimeDog** [comment]
I was thinking only that OP would be able to perform this magic. I was expecting that a bag of gold (or ingot, or whatever) would be converted to cash whenever a player touched it. The idea was to be able to gift a player: drop it at their feet or put it in a chest. In either case, when they pick it up, it is converted. That seems a lot simpler to me, and removes the need for a lot of specialized code to let players store bags.

**Comment by Rocologo** [comment]
Yea, well you talked about a sign too :-) and a sign will demand the above features.

So I think you would like to have this feature first.

Admin command:
/mh money drop amount
-  to drop some money in front of you. Question is if the money should be take from the player who executes the command or the server?

**Comment by SlimeDog** [comment]
From the server. The same "account" that funds mob kills. :)

**Comment by Rocologo** [comment]
You can do /mh money drop <amount> in V4.5.0

**Comment by SlimeDog** [comment]
Spigot 1.11.2, MH 4.5.0.

> /mh money drop 1

did not drop anything on the ground. Also, the text includes a decimal

> You dropped 1.0

**Comment by SlimeDog** [comment]
Same with MG 4.5.1.

**Comment by SlimeDog** [comment]
MH 4.5.2

Still seeing a Steve head when I drop a bag.

**Comment by SlimeDog** [comment]
I think it is a mistake to invent another full-blown economy. I like the drop that you implemented, as an adjunct to my existing economy. It's just a pretty visual way of giving money.

**Comment by SlimeDog** [comment]
The bag of gold can drop a significant distance away from me.  If I am close to a stairwell, it may even drop down to the next floor (floors are Y=4 apart). Please drop the bag close by, and on the same Y level.

**Comment by Rocologo** [comment]
You have to look at the block where you want the money dropped.

**Comment by SlimeDog** [comment]
Oh. Well, then...

**Comment by Rocologo** [comment]
Please try newest build, I have changed the way i calculate where to drop the bag. Distance will now be max 20 blocks from you, in the direction you look. 

You can also use /mh money drop <player> and the the bag will spawn 3 block ahead in the direction the player look.

http://jenkins.lindegaard.one:8180/job/MobHunting/

I have made the other commands too: give,take,buy,sell but give+take does not remove the items from the inventory. (BUG). I need to sleep now, and do not have much time tomorrow.

**Comment by SlimeDog** [comment]
Spigot 1.11.2, MH 4.5.3-b292.

Drop seems fine. I did not test the other commands. The head is still Steve, not Bag of Gold. :(

**Comment by Rocologo** [comment]
No. I dont understand why some of you get a Steve head. I do still get the bag of gold. This is something i really cant do anything about. Its all about how Minecraft (and Mojang) chooses to update the heads. The thing is that Im using a method created by InventiveTalent, who also made http://mineskin.org

If the method does not work I cant fix this, then you have to go back to the gold ingot :-(

**Comment by Rocologo** [comment]
in fact I use the same method for making all heads, inclusive the mobs heads, when you get one of these in your inventory, after a kill.

**Comment by SlimeDog** [comment]
I don't understand it. I just removed the entire plugins/MobHunting/ directory and restarted the server, to regenerate the default configuration. The same problem with heads occurred.

I did not experience this issue until the money-drop-command update. As a test, I reverted to MH 4.4.8, with no other changes to my system. MH 4.4.8 does not contain the money-drop-command, of course. But when I kill a mob, I see the correct Bag of Gold drop. So I posit that something about the head handling changed since that release.

**Comment by SlimeDog** [comment]
If you can back out all of the economy code, except money-drop, I could quickly test it.

**Comment by Rocologo** [comment]
I don't know how to solve the "Bag of gold" texture problem, I have tried to change the UUID, to see if this helps.

Please test Build 293 or newest, tell me if this works...
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment]
I didnt see this until now : _I did not experience this issue until the money-drop-command update. As a test, I reverted to MH 4.4.8, with no other changes to my system. MH 4.4.8 does not contain the money-drop-command, of course. But when I kill a mob, I see the correct Bag of Gold drop. So I posit that the new drops/currency code changed something about heads. It's most likely an interaction with some other plugin, but it is presented by MH._ this tells me that Build 293 will fix the "Bag of Gold"

**Comment by SlimeDog** [comment]
293 does not fix the bag-of-gold issue.

**Comment by Rocologo** [comment]
Try picking up a head and place it as a block, and then break it again, a couple of times, to see if this fixes the problem like it did on my server????

**Comment by SlimeDog** [comment]
Did you want me to place and break the bag-of-gold head? or some other head? What command do I use to get a bag-of-gold head? I tried the following:

> /mh money give _playername_ 5

That dumped the money into be economy balance. I'm not fast enough to see if there was a flying head temporarily.

> /mh head _playerName_ _playerName_

That gave me my own head. I placed it on a wall, then broke it. Several times. No change in the MH drop result.

> Grab a copy of the bag-of-gold I use, from a commandblock

Placed it on a floor, then broke it. Several times. No change in the MH drop result.

What else should I try?

**Comment by Rocologo** [comment]
If you set "drop-money-use-item-as-currency: true" you can pick up and carry, break and place, buy and sell the bag of gold. This was what i did....

**Comment by SlimeDog** [comment]
Test protocol:

Part 1
- Start server
- Drop money, which displays Steve head
- Stop server

Part 2
- Configure "drop-money-use-item-as-currency: true"
- Start server
- Drop money, which displays correct Bag-of-Gold head

So something in the "drop-money-use-item-as-currency: false" (ie., lack of currency: true) code is causing the problem.

**Comment by Rocologo** [comment]
I worked alot on v4.5.4 to fix this issue. Please help me test v4.5.4

**Comment by SlimeDog** [comment]
Confirm that with
> drop-money-use-item-as-currency: false

MH 4.5.4 drops  perform as expected:
- skin is my bag-of-gold: [mineskin.org/6875](https://mineskin.org/6875)
- funds are added to my economy balance on pick-up
- no bag in inventory.

All correct.

**Comment by Rocologo** [comment]
Yes!!!! 

I saw that skin yesterday, and I liked it, I actually thought about using your,  as default, because it does not have the $...

**Comment by SlimeDog** [comment]
Agreed. I like it much better. That's why I used it.
