### ISSUE TITLE
Feature request: New stat

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#156]
Please add something like
> /mh stat total_rewards _period_

EDIT: and the necessary data collection and storage.

**Comment by Rocologo** [comment]
please explain what total_rewards is?

**Comment by SlimeDog** [comment]
Based on the values in config.yml, I get some amount of reward for each kill. I would like a leaderboard with the total rewards earned in a period. Something like total_kills, but multiplied by the value of each kill, including bonuses. I believe that the relevant data are not stored now, but they could be. :)

**Comment by Rocologo** [comment]
Is total_reward the amount of money?

**Comment by SlimeDog** [comment]
> Is total_reward the amount of money?

Yes. It would be even better to record total_rewards_base and total_reward_bonus.

**Comment by Rocologo** [comment]
It will only be TOTAL_CASH

**Comment by Rocologo** [comment]
I have made the first tests and it worked, after some bugfixing. But I realized a "problem"

There are many ways to count the money:

1) Each time the player kills a mob I can record cash immediately. This is easy and this is how it works now.

BUT 

2) What if the money is dropped on the ground? Then I could record the money picked up. 

BUT

3) Then the player can pickup other players money on the ground, or money dropped by admins 

BUT 

4) What if the Bag of gold is in the players inventory, should the money the be counted? And what if the player droppes the bag of gold on ground, then he dont get the cash?

Non of the above methods is 100% correct, maybe I should stick with 1). Or drop the idea?

**Comment by SlimeDog** [comment]
My preferences would be:
1. Works if the server is configured for immediate cash out.
2. By definition, the player doesn't own the money until it is picked up and converted to cash.
3. Special cases
a. Perfectly alright with me. :)
b. Admin drops are not kills. I was thinking total cash from kills.
4. Inventory is not cash. Count it when converted to cash. That covers both cases, I think.

Bear in mind that I am not using bags as a currency
> drop-money-use-item-as-currency: false

Others, if any, who want to use it as a currency, should advise.

**Comment by Rocologo** [comment]
Because of the discussion about the **metrics** I have decided to take a break from developing on MobHunting and doing support. 

Since I dont get support from the  more than 300 server owners on how I want it, I dont have the fun anymore. So why continue???

I will make one final release where you get option 1, because I have made it like this. 

I might even publish a version where the heads has a value. I think it will be default 0.

**Comment by SlimeDog** [comment]
I'm very sorry to see the way the discussion has gone. As I said publicly, I would very happily pay for a Premium plugin. But 300 x (choose a number) is not a lot of income, either. So it places developers in a bind. Eventually, so many plugins go abandoned. :(

**Comment by Rocologo** [comment]
I did never develop because I wanted to earn money. And 300 x what the users would pay could pay me a descent salary anyway. 

I don't know if I will abandom MobHunting, but I will take a LONG break. after this final(next) release. 

You will get the TOTAL_CASH, MINECRAFT_CASH, SPIDER_CASH.... statistics in next version. I will count the money dropped, **not** what the player picks up.

**Comment by SlimeDog** [comment]
Thanks for everything you have done.
