### ISSUE TITLE
pass event EntityDeathEvent to MobHunting v4.7.7

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#218]
Updated your plugin yesterday and woke up to this this morning
https://pastebin.com/y2pqQf3c

Thanks for looking

**Comment by Rocologo** [comment]
I'm missing some of the most important lines in your log. (You have to open the the log file in a text editor and then make cut&paste) to give the full log...

Multicraft removes some of the lines, and in this case the most important lines....
17.04 08:23:09 [Multicraft] Skipped 17 lines due to rate limit (30/s)

BUT this error might be fixed with Build 345, please test it
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by krustymk** [comment]
https://pastebin.com/P5RfW6Ut

From the log

It seems to be happening at one guys zombiepigman farm in the nether, not noticed it anywhere else..
Ill give the new build a whirl, thanks :)

**Comment by Rocologo** [comment]
You have tested on V4.7.7, (Could not pass event EntityDeathEvent to MobHunting v4.7.7)

You need to test Build 346 V4.7.8-SNAPSHOT. This error should be fixed in this snapshot.

**Comment by krustymk** [comment]
All good so far, chap hasnt been on whilst i was so i could check his farm
Thanks for your help :)

**Comment by Rocologo** [comment]
Released V4.7.8 :-)
