### ISSUE TITLE
Fishing achievements not working

### ISSUE THREAD

**Issue by vilgrar** [Rocologo/MobHunting#231]
MobHunting will not register caught fish, preventing related achievements from starting. I've tried with and without McMMO and there's no difference.

I tried all types of fish:
- Raw fish
- Salmon
- Pufferfish
- Clownfish

Money rewards and head drops work as intended, though.

**Comment by Rocologo** [comment]
Unbelievable! I have found the bug and could see that this has never worked! Nobody else has tested and noticed this bug.

This is fixed in build 374 : https://fractal.lindegaard.one:8181/job/MobHunting/

Please notice when you test this. Sometimes when you fish, it is recorded that you have caught a fish but you did not get any in your player inventory. This is how Minecraft works at the moment. I this case the Fish (the item) is laying in the water. The Fishing status does not show this status so I am not able to change this behavior.

**Comment by vilgrar** [comment]
Confirmed. Build 374 fixes the issue. All types of fish achievements work as intended.
