### ISSUE TITLE
INFO Could not pass event EntityDeathEvent to MobHunting v4.9.4

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#249]
INFO Could not pass event EntityDeathEvent to MobHunting v4.9.4

https://pastebin.com/dr1A8rhS

**Comment by Rocologo** [comment]
You need to extract the error from the log file, Multicraft has skippeded the most important lines, the lines where it says "caused by"....

11.06 09:35:39 [Multicraft] Skipped 11 lines due to rate limit (30/s)

I cant fix this error unless I can see where the bug is :-)

**Comment by krustymk** [comment]
https://pastebin.com/5YnWpsNk

Caused by: java.lang.NullPointerException

thanks for your help

**Comment by Rocologo** [comment]
This is a strange bug. It looks like a mob dies with a "null" location??? Maybe this happens if a mob fall down under bedrock....

I have added a test to check if the location is null. I build 411.

Please test. Build 411 or newer.
https://fractal.lindegaard.one:8181/job/MobHunting/

And let me know if you still see this bug?

**Comment by Rocologo** [comment]
Please let me know if this is a problem in V4.9.5?
