### ISSUE TITLE
dragonslayer egg drop from dragon not happening with mobhunting enabled

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#256]
im using dragonslayer to control end and enderdragon stuff,
https://www.spigotmc.org/resources/dragonslayer.36250/
the dragon is configured to drop an egg as item, and it doesn't happen with mobhunting installed on server, when i take off mobhunting, the egg drops fine. i will gather debug info now

**Comment by chillerkraft** [comment]
https://pastebin.com/eJae8tHw

hmm maybe you removed the egg because i was in creative mode?
but you still gave me the money?? :/
anyways ill see if i get the egg dropped while in survival mode

**Comment by chillerkraft** [comment]
yea that's what it was
ill leave this issue open because maybe it's not right that i still get payed for killing in creative and god mode?

**Comment by Rocologo** [comment]
Yes, you do not get an egg because you was protected by creative mode

19.06 20:51:42 [Server] INFO [MobHunting][Debug] ======================== New kill ==========================
19.06 20:51:42 [Server] INFO [MobHunting][Debug] CHILLERMART killed a EnderDragon (Minecraft)
19.06 20:51:42 [Server] INFO [MobHunting][Debug] Permission 'mobhunting.mobs.*' or 'mobhunting.mobs.ENDER_DRAGON' not set, defaulting to True.
19.06 20:51:42 [Server] INFO [MobHunting][Debug] KillBlocked: CHILLERMART is in creative mode
19.06 20:51:42 [Server] INFO [MobHunting][Debug] Removing naturally dropped items
19.06 20:51:42 [Server] INFO [MobHunting][Debug] Removing naturally dropped XP
19.06 20:51:42 [Server] INFO [MobHunting][Debug] ======================= kill ended (28)======================

But maybe I am wrong? I cant remember how it is with the dragon and creative mode? can you die while figthing the dragon in protected mode?

**Comment by Rocologo** [comment]
And if you are in Essentials God mode, the rewards will be disabled too.

**Comment by chillerkraft** [comment]
but i'm still getting paid even though i am in creative and god mode. i think that is a bug

**Comment by Rocologo** [comment]
Do you get money ???? (or a bag of gold) The debug information does not show this???

And immediately after the 4 lines
19.06 20:51:42 [Server] INFO [MobHunting][Debug] KillBlocked: CHILLERMART is in creative mode
19.06 20:51:42 [Server] INFO [MobHunting][Debug] Removing naturally dropped items
19.06 20:51:42 [Server] INFO [MobHunting][Debug] Removing naturally dropped XP
19.06 20:51:42 [Server] INFO [MobHunting][Debug] ======================= kill ended (28)======================

MobHunting "stopps" and is not able to deposit any money. Are you sure this is not dragonslayer which gives you money? I dont think I am able to stop that.

**Comment by Rocologo** [comment]
I looked at DragonSlayer config file and can see that you can set a reward there. It looks like there is no API, where I can stop this, so you will have to talk to the dev of DragonSlayer

BUT If you set this value to 0 in DragonSlayer config and enter the value in the MobHunting config then you will not get any money for killing a enderdragon in creative and god mode.

**Comment by Rocologo** [comment]
Can I close this one?

**Comment by Rocologo** [comment]
Fixed in v5.0.0
