### ISSUE TITLE
inv full and getting a head drop doesn't add it to inv or drop it

### ISSUE THREAD

**Issue by chillerkraft** [Rocologo/MobHunting#260]

**Comment by Rocologo** [comment]
Please be more specific. I dont understand what you are trying to do and what happens? 

I must be able replicate the bug, if I am going to fix it.

**Comment by chillerkraft** [comment]
so, have a full inventory, and then kill mobs until you get a head drop from a mob. u know how it adds it right to your inventory? it doesn't happen or drop even when inventory is full.
no big deal i guess but just wanted to tell u

**Comment by Rocologo** [comment]
Yes, Now I understand what you at doing. I will take a look at the code.

**Comment by Rocologo** [comment]
I checked on my test server and the mobs head is actually picked up ( I tested on the enderdragon head)

BUT if your heads has a value, they cant be stacked, because of the value. Two equal head can have different values, and if I merge the items, i would have to merge the value into one number, but what happens then if the player drops on head, then I dont know the original value of the head.

Does your heads have a value (>0$)

**Comment by Rocologo** [comment]
Can I close this one?

**Comment by Rocologo** [comment]
This should be fixed in V5.0.0
