### ISSUE TITLE
Toggle Grinding detection message

### ISSUE THREAD

**Issue by DawgZilla** [Rocologo/MobHunting#267]
Is there a way to toggle the grinding detection notification?
I haven´t found a solution to disable the user notification.

We do have monster farms, but we don´t want to get spammed by the plugin.

Thank you in advance.

**Comment by Rocologo** [comment]
Im not sure if I understand you question? What user notification are you talking about?

1) You can disable grinding detection in config.yml
or 
2) You can whitelist areas where you have monster farms, to allow users to get rewards.

**Comment by DawgZilla** [comment]
When I kill a mob in my endermanfarm, I will receive the message that this server is blacklisted by grinding protection. I have to look for the correct sentence.

Anyway.
This message will repeat after killing a mob.
The grinding detection works flawless, but the notification should be turned off because grinding a farm is allowed to gain experience instead of money.

Next thing I wanted to ask you is how´d you handle assist kills.
When 2 players kills a mob, the person who actually killed the mob will get a message, whereas the assistant doesn´t get a message.
For somehow the amount of money will be deposit on the players wallet.
Unfortunately it is not clear how the value is being calculated. I have no control to handle assist kills properly. 

Sometimes we´ve got a pretty strange issue...
When player a and player b kills a mob - debug log says:
 
player a was assisted by player a. Reward/Penalty is only ½ (20 dollar 14 cents)

We really appreciate the hard work and the result of this beautiful plugin. I hope you will continue supporting this plugin for a while. As a programmer, I can imagine how time consuming supporting plugins could be. 

I really would like to make my first donation to a minecraft plugin when things are going well for us.

**Comment by Rocologo** [comment]
Grinding: Okay I think I understand now. You have not disabled grinding detection, but you allow xp, although the players is actually grinding.  This is the reason why you get the messages. The player are grinding and for that reason they dont get money, and then they get the message.  No matter if you allow xp rewards or not. The are grinding :-) XP is not a MobHunting reward.

Assisted kills: If two player hits the mob they will share the reward 50/50. The player who kills the mob in the end will get a bag of gold where the mob dies, player two will get the money directly in his pocket, because where should I else place his cut??? 3 blocks from  where the mob dies? :-) 

I have looked at the code at it looks to me that both players get the message about the half reward. But this is really hard for me to test - because I am all alone on my test server :-) 

I usually test using MyPet, if I hit a mob and let my mypet kill the mob the I get the message about the half reward.

If you still are having problems with this or think you have found a bug, then I will need the debug information from the console. You enable debug using /mh debug.

So you are a developer your self ? But not Minecraft Plugins? And yes I spend more hours on this than I will EVER admit! :-)

**Comment by Rocologo** [comment]
No answer. closing ticket
