### ISSUE TITLE
[bug] Wither Skeleton heads drops Vanilla and MobHunting Head.

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#314]
The most hunted mob head by players is obviously the Wither Skeleton, so they can make wither bosses, so they can get beacons. 
At present MobHunting allows Wither Skeletons to drop their default vanilla head and also the chance of the MobHunting head, I know this as they are named differently! 
One says wither skeleton (MobHunting) and the other is "wither skeleton skull". 
Now I like the natural idea of when players use a looting enchant on their weapon to kill a mob that their chances of the drop are greater https://minecraft.gamepedia.com/Wither_Skeleton#Drops

> They have 2.5% chance of dropping a
> Wither Skeleton Skull when killed by the player, and Looting increases the chance by 1 percentage point per level (up to 5.5% chance op a drop with Looting III).

Im suggesting 2 things.

1. All Wither Skeleton heads are dealt by the plugin, only if no 2 is implemented;
2. Add the option for looting enchant to change the drop-rate. 
    - `sheep-cmd-run-chance: 0.1` could be `sheep-cmd-run-chance: (0.025-0.055)` highest run-chance with loot 3 on item.

**Comment by Rocologo** [comment]
I like the idea about using the enchantment for something :-)

But because I spend more time on developing this plugin than I play the game :-) I dont know much about Enchantment and also I was now aware that the Wither Skeleton head could be used for something... So I have never tried to make a Wither boss...

**Comment by Rocologo** [comment]
I just learned to make a wither boss... Im happy that I left my normal test area before I spawned the Wither Boss... Must of the area was destroyed, before I killed it :-) I used MobHunting Wither Skeleton heads, so I know they works like the normal heads....

So I not sure what the problem is? What do you mean with "All Wither Skeleton heads are dealt by the plugin" ? I dont handle "Wither Skeleton head" I just give them a value... ?

**Comment by FrozenBeard** [comment]
Yes the heads work to make it! thats the not the issue! The issue is the **DROPS**. The default mechanic of minecraft, drops wither heads with a 2.5-5.5% chance without MobHunting. 
Please read what I linked.
https://minecraft.gamepedia.com/Wither_Skeleton#Drops

So what's happening, is there is the default mechanics can drop a head and ALSO MobHunting can drop a head.

**Comment by Rocologo** [comment]
Ahhh I just read the title... If you kill a Wither Skeleton there is a chance that Minecraft drops a Wither Skeleton head and there i a change that MobHunting drops a Wither Skeleton head....  This is true... Im not sure I should change this, if the server owner disables the wither_skeleton_-run-cmd or removes the head command then the players would never get wither skeleton heads....

**Comment by Rocologo** [comment]
Could you please test this with the new config.yml ? 

please make a complete backup of the MobHunting folder before installing a 5.4.7 Snapshot! So you are able to restore fast if there are bugs!

**Comment by Rocologo** [comment]
V5.5.0 released, where you have a % per cmd
