### ISSUE TITLE
Grinding penalty is not working with slimes

### ISSUE THREAD

**Issue by Waterman1001** [Rocologo/MobHunting#354]
Hello,
It seems like the grinding penalty is not working for the slime mob.
People on my server are currently having huge killstreak and other bonusses because of slime farms they have made. They do not get the grinding penalty.
I love this plugin and it is amazing so I hope you could have a look at it.
Thanks in advance! :)

- Waterman1001

**Comment by Rocologo** [comment]
I will see what I can come up with. The splitting nature makes it hard to solve, but it should be easy to disable killstreak when its a slime

**Comment by Rocologo** [comment]
I thin this is fixed in newest SNAPSHOT. Do you have e test server, where you can test my newest snapshot? 

its VERY important that you make a complete backup of the MobHunting folder before you try Build 579 or newer. I have made MAJOR changes in the config.yml. And I need more people to help with the testing.

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
Fixed in V5.5.0
