### ISSUE TITLE
Issues with new configuration

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#362]
The config keeps backing up after every restart, even if I completely reinstall MobHunting it still creates empty backups.

It also keeps resetting the ''messages'' part of every mob and fishing rewards are not working.

https://pastebin.com/RuEjsxZh

**Comment by Sikatsu** [comment]
Enabling /mh debug gives me another backup made: https://pastebin.com/dPRffn54

**Comment by Rocologo** [comment]
Agree somethings wrong with the fishing. 
mh debug'save a backup, because the config changes. 

Please test build 593 
https://fractal.lindegaard.one:8181/job/MobHunting/

The messages works better and if the message is empty, the line is removed from the config.yml. Remember to make a backup of your config.yml !!!

I have to go for some hours, but I will look at the fishing problem when Im back

**Comment by Sikatsu** [comment]
So every /mh debug gives a backup of the config, aswell for every restart or clean install?

I think when you just install the plugin for the first time, it shouldn't make backups?

Would love to have the fishing issues fixed, players complain about it.

**Comment by Rocologo** [comment]
I think v5.5.3 fixes everything.

I only make a backup on server start now.

Fishing rewards works - i had forgot that changed from "disable_fishing_rewards" to "enable_fishing_rewards" in config.yml

**Comment by Sikatsu** [comment]
But I don't need a backup on every start.. I'm already using the new configuration.

Fishing is fixed indeed.

Also after every restart the ''messages'' line comes back, super annoying. Also after 5.5.3.

http://prntscr.com/imupe7

**Comment by Sikatsu** [comment]
And removing the line and doing /mh reload doesn't work.
