### ISSUE TITLE
Unable to exchange head from "drop_money_on_ground_itemtype: KILLED"

### ISSUE THREAD

**Issue by bc-hill** [Rocologo/MobHunting#368]
Example head:
![image](https://user-images.githubusercontent.com/7044511/37071931-d96160c2-2173-11e8-9e38-815bb3d7f58a.png)

You stated on the [Spigot discussion](https://www.spigotmc.org/threads/mobhunting.46937/page-161#post-2916839) that these heads with associated value can be exchanged with "/mh money sell" or a [bagofgold] sign.

Trying to use the sign results in the message "You must hold the Bag of gold in your hand to sell it.
Running the command "/mh money sell" does not return anything.  
Running "/mh money sell 1" returns "You have no Bag of gold to sell"

`This server is running CraftBukkit version git-Spigot-4bd94dc-3a482bd (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
`
`This server is running 'MobHunting 5.5.6'.
`

Thank you!

**Comment by Rocologo** [comment]
I think I found the bug. Please test build 599 or newer
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment]
I have just tested "/mh money sell" and it works. You have probaly used "/mh money sell 1" and then it does not work. The thing is that you have to sell the "hole head" and not 99% of its value. :-) Its only bagofgold where you choose to sell 99% (Because it is similar to a bag with coins)

Maybe I should make a change so when a player use "/mh money sell x" he sell the hole head, or at least give a message which make sense?

**Comment by bc-hill** [comment]
No, I was trying "/mh money sell", but had forgotten that it is the command that sells what is in your hand.  My bad.  Thank you for resolving this issue!!
