### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent (1.13)

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#417]
This error comes when a phantom attacs you: https://pastebin.com/5aRuLK9F

**Comment by Rocologo** [comment]
Youbare missing the last and most important lines in the error text

05.08 17:45:07 [Multicraft] Skipped 25 lines due to rate limit (30/s)

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: Nesseley <notifications@github.com>
Sendt: søndag, august 5, 2018 4:48 PM
Til: Rocologo/MobHunting
Cc: Subscribed
Emne: [Rocologo/MobHunting] Could not pass event EntityDamageByEntityEvent (1.13) (#417)


This error comes when a phantom attacs you: https://pastebin.com/5aRuLK9F

**Comment by Nesseley** [comment]
https://pastebin.com/sUxfWFA1
I am using http://builds.enginehub.org/job/worldguard/10262 this build of worldguard

**Comment by Rocologo** [comment]
Ahh yes, I have tried the same build, but it sems that the dev has not yet implemented the CustomFlag. I have written to the dev on his forums. I could not find where to create tickets. Im not sure if he even answers me, because we use this build.

If this is your only problem with this WG build you can choose to disable WorldGuard integration in MobHunting config.yml. And wait until the dev releases a version with customflags or points me in another direction on how to solve this.

If you disable wg integration mobhunting will not detect if players kill mobs while being protected by a region with mob-damage deny.

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: Nesseley <notifications@github.com>
Sendt: mandag, august 6, 2018 6:27 AM
Til: Rocologo/MobHunting
Cc: Rocologo; Comment
Emne: Re: [Rocologo/MobHunting] Could not pass event EntityDamageByEntityEvent (1.13) (#417)


https://pastebin.com/sUxfWFA1
I am using http://builds.enginehub.org/job/worldguard/10262 this build of worldguard

**Comment by Nesseley** [comment]
Disabling integration sounds good ot me, not using it anyway ^^
