### ISSUE TITLE
Add option for Towny - disable_rewards_in_all_towns

### ISSUE THREAD

**Issue by Nesseley** [Rocologo/MobHunting#445]
You already have disable_rewards_in_home_town: true which is great. 

But I want players to not get money in any town.
A option to disable rewards for everyone in every town would be great :)

**Comment by Nesseley** [comment]
The problem is that right now you only block owners of a town from getting money in the town. Everyone else can earn money while inside the town.

And yes, I only want rewards in wilderness

**Comment by Rocologo** [comment]
At the money I only deny getting money if you are protected by the town. I think it is okay to get money if you kill a mob while not protected - even if you are in a town. 

Town owner and members should not get rewards because they are protected against damage, everyone else is not and should therefore get the money.

**Comment by Nesseley** [comment]
Well members of my town can make money inside the town that they are a member of, so something is not working.

**Comment by Rocologo** [comment]
Please test newest build. I have added "disable_rewards_in_any_town" for you

https://fractal.lindegaard.one:8181/job/MobHunting/
