### ISSUE TITLE
ERROR Could not pass event EntityDeathEvent to MobHunting v6.5.1

### ISSUE THREAD

**Issue by rybuilder23** [Rocologo/MobHunting#476]
hello when i kill a mob i get this message! 

```
rg.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1704) ~[MobHunting-6.5.1.jar:?]
02.02 12:51:41 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType
02.02 12:51:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1855) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1336) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1044) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:568) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO org.bukkit.event.EventException: null
02.02 12:51:41 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v6.5.1
```

**Comment by Rocologo** [comment]
This is because you the new McMmO instead of McMMO classic. Use classic or disable integration in config.yml



Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: rybuilder23 <notifications@github.com>
Sendt: lørdag, februar 2, 2019 12:55 PM
Til: Rocologo/MobHunting
Cc: Subscribed
Emne: [Rocologo/MobHunting] ERROR Could not pass event EntityDeathEvent to MobHunting v6.5.1 (#476)


hello when i kill a mob i get this message!

rg.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1704) ~[MobHunting-6.5.1.jar:?]
02.02 12:51:41 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType
02.02 12:51:41 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1855) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1336) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1044) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:568) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[server.jar:git-Spigot-f56e2e7-b634e05]
02.02 12:51:41 [Server] INFO org.bukkit.event.EventException: null
02.02 12:51:41 [Server] ERROR Could not pass event EntityDeathEvent to MobHunting v6.5.1

**Comment by Rocologo** [comment]
In next release i will switch to the new McMMO
