### ISSUE TITLE
Problem with LogBlock

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Rocologo/MobHunting#577]
Hello, on my server the moderators have noticed that the heads created by MobHunting logblock do not register them well. Only record when placed, not when they break.
I don't know since which version it happens, they just realized yesterday.

The server is in the last compilation of spigot 1.14.4 and the last of logblock and mobhunting

PD: I contribute video showing it.
https://www.youtube.com/watch?v=gtjdxo58aOo&feature=youtu.be

Regards.

**Comment by NeverGrowUp** [comment]
Can confirm with the above.
After repeated testing and server restarts, any version from 6.8.6 and onward you lose the mobhead when breaking it from a wall or from the ground. (this includes latest 6.9.3)
But going back to version 6.8.5 is fine but brings back the head pop when there is a block update next to a mob head.

**Comment by Rocologo** [comment]
Let me get this right.

1) You place a head on the ground
2) You break it
3) You restore the head using LogBlock (IS THIS CORRECT?)
4) head looses its value when you break it.

If this is correct the problem is not 4, it is no 3 - you cant see this, but the bag/head losses actually its value when LogBlock does not restore the item correct. You can verify this by restarting the server and click on the head/bag with a stick. The you will see that the problem happens before 4)

**Comment by Rocologo** [comment]
Please confirm if this is what you do?

**Comment by Rocologo** [comment]
After looking at the video I understand that you only test the deleting of the head is detected using the compass. And I see clearly it is not. 

The problem is the there is currently no way to store MetaData in the Minecraft data model on server reloads. Therefor I have to store the reward information in the rewards.yml file, so I can load all placed rewards when the server starts.

I have currently now way of solving the problem. Only thing I can think of, is that you could ask the LogBlock developer to add support for MobHunting/BagOfGold rewards. My guess is that he will not.

**Comment by Mundo-Minecraft** [comment]
I had already created a report in LogBlock, I just added this report to read it. Let's see if we are lucky.

A few months ago report something similar with the beacon, record when it is placed but not when it breaks.  I solve it as soon as someone explained it better than me :)

https://github.com/LogBlock/LogBlock/issues/762

Thank you.
