### ISSUE TITLE
MobHunting lag

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#587]
Hey there,

According to people on spigot, they say it would be best to look into / disable MobHunting since it's causing quite some lag on my server.

I don't wanna do that since it's a core plugin on my server (due to happy hour) so I was wondering if theres any improvement you can make?

https://timings.aikar.co/?id=4f9ebf2aa1544d6889577e235e6f8037

Kind regards,

Sikatsu

**Comment by Rocologo** [comment]
I have heard the rumors but Im still not sure if this is correct. And to be honest it is hard to read the Timings reports. 

Do you have lag on your server? 

Im looking on the BlockPhycicsEvent - It might be the problem - and If the this is the case it might be that you have too many Mobhunting Heads or BagOfGold bags placed on the ground. Because I need to do alot of testing when a player / or water / or other actions try to change the MobHunting blocks. 

Do you have many MobHunting blocks on your server? (You can check this by counting the rewards in the rewards.yml file)

**Comment by Sikatsu** [comment]
Yes, the lag is really bad even. I do think a lot of mobheads are placed in the world. More being placed everyday. Currently i'm on my phone, and it says the rewards.yml file is way to big to be opened without a proper file management tool. Not sure why's that, lol.

**Comment by Sikatsu** [comment]
Would disabling these mobheads solve it for now? Or any other tips you can give me?

https://timings.aikar.co/?id=8d16dc6380e94b0ab60bb1c1a6bd7fb9

**Comment by Rocologo** [comment]
plaese test newest build here: https://fractal.lindegaard.one:8181/job/MobHunting/

I have disabled Restone Powered Mobhunter Signs because I think they cause the lag.

**Comment by Sikatsu** [comment]
I doubt that's the case, as I don't use signs from MobHunting?

**Comment by Rocologo** [comment]
Maybe not... but this feature examines alot of blocks... no matter what... I'm petty sure this will improve the lag problem. So please test.

**Comment by Sikatsu** [comment]
Will let you know tomorrow!

**Comment by Sikatsu** [comment]
It does seem to be better, I don't see MobHunting in my recent timings anymore. 
I didn't use any redstone powered signs though.

I'll let you know if it ever pops up high again, but it seems to be fixed!

**Comment by Rocologo** [comment]
I understood that and it didnt matter if you used powered signs or not. Problem is that I had to look for redstone_lamp changes all the time, which was very ineffective, which I think caused the lag. 

Redstone powered signs can still  be enabled in config.yml though

**Comment by Sikatsu** [comment]
Makes sense, thanks for looking into it!

**Comment by Sikatsu** [comment]
This seems to be resolved.
