### ISSUE TITLE
Renaming Mob Skull Heads

### ISSUE THREAD

**Issue by SpaZMonKeY777** [Rocologo/MobHunting#61]
Figured I would also open a ticket to maybe work on a feature or alteration to make the head drop command a bit cleaner. Rather than showing the player/account's name on the head, showing just a normal mob/monster name on the skull looks quite a lot better and garners a lot less questions from players lol.

Here is what I got so far for renaming:
/give player 397 1 3 {SkullOwner:"MHF_Wither",display:{Name:Wither}}

So this will rename the skull 'Wither' instead of 'MHF_Wither' when given to the player. Sadly if a player places the skull, and then breaks it, the name reverts back to it's default skin name 'MHF_Wither' and no way for the player to fix. Think there's anyway to make it permanent like they do with the [PlayerHeads ](http://dev.bukkit.org/bukkit-plugins/player-heads/)plugin?

**Comment by Rocologo** [comment]
Thanks for the info I have added ,display:{Name:.....} to the default config.yml and then I think I will make my own /mh head command to MobHunting. This is the only way I can handle what happens when a player breaks the head. I dont think it can be fixed permanent, but I can catch the place event and the break event an rename the head again. I guess this is what they do in PlayerHeads.

The permanent change will take some time to make and it will therefore not be in next release.

I will keep the ticket open - to remember the change / wish.

**Comment by Rocologo** [comment]
please test /mh head spawn mobname displayname amount xpos ypos zpos
or short version /mh head spawn mobname

See the update 3.2.4. This is only first release, so there might still be some bugs.

**Comment by Rocologo** [comment]
You can also do "/mh head rename displayname" now

**Comment by Rocologo** [comment]
This can be done with v3.3.0
