### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v7.0.8

### ISSUE THREAD

**Issue by Weasel-Beans** [Rocologo/MobHunting#644]
Errors: https://pastebin.com/vNbarMQE

Timings: https://timings.aikar.co/?id=409fb35d2ba34f3fb4ec0ada9984f69b

**Comment by Rocologo** [comment]
I think this i fixed in newest SNAPSHOTS

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

Please take backup before updating to BagOfGold 3.0.0 or MobHunting 7.5.0 I have mad big and many changes in these builds.

I need help with the testing. 

When you use ANY one of these two build you will get some new files in the folder BagOfGold called bagofgoldcore.yml and bagofgoldcore.db. The both contain shared settings / data used by both plugins. 

It also contain the new mobs in MC 1.16.1 (Hoglin, Piglin, Strider and Zoglin)

Please create a new ticked if you find new bugs.
