### ISSUE TITLE
Support 1.16.1 and RGB colors

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#652]
Hey there! Are you planning to update to 1.16.1 and add support for the new RGB colors? ^^

**Comment by Rocologo** [comment]
Yes. Im planning to update to 1.16.1.
 Im not aware sbout the new festures so I dont know how it will affect my two plugins.

Unfortunately Im on vacation now so I have very limited computer time 😒

**Comment by Sikatsu** [comment]
I think the biggest change in 1.16.1 are the new RGB colors, that allows you to basically use any color rather then the default 15 colors minecraft always had. I am planning to change my servers color scheme because of that, and since mobhunting is a core plugin of my server, it would be nice if that's possible. ^^

Enjoy your vacation!

**Comment by Rocologo** [comment]
I think this i fixed in newest SNAPSHOTS

https://fractal.lindegaard.one:8181/job/BagOfGold/
https://fractal.lindegaard.one:8181/job/MobHunting/

Please take backup before updating to BagOfGold 3.0.0 or MobHunting 7.5.0 I have mad big and many changes in these builds.

I need help with the testing. 

When you use ANY one of these two build you will get some new files in the folder BagOfGold called bagofgoldcore.yml and bagofgoldcore.db. The both contain shared settings / data used by both plugins. 

It also contain the new mobs in MC 1.16.1 (Hoglin, Piglin, Strider and Zoglin)

Please create a new ticked if you find new bugs.

I have NOT looked at colors yet.

**Comment by Sikatsu** [comment]
Seems to work fine, but zombie_pigman should be zombified piglin.

I also catched this error: https://pastebin.com/rGFY9e6X

As for color support:

https://pastebin.com/SfAhybZD

https://pastebin.com/Ks3J4tu5

What's this BagOfGold? Do we really need that when I just wanna use mobhunting? I am just looking for a simple plugin that gives money from mobs and happyhour, don't need all the bloatware if possible! haha :P

**Comment by Rocologo** [comment]
Both my plugins use the Bags so I had to maintain the source code twice when a bug was found. I have moved the code to BagOfGoldCore. You dont need to install anything, but as a MobHunting user only, you will find a BagOfGold folder in the plugins folder and shared settings in bagofgoldcore.yml 

Thank you for the code snippets, but Im still thinking about how to use it.

**Comment by Sikatsu** [comment]
Thanks for clarifying though!

This code allows for use of {#RRGGBB} formatting within translation files ^^

**Comment by Rocologo** [comment]
Thank you, it looks like a good choice for the format.

**Comment by Rocologo** [comment]
I forgot to mention that the concurrent modification bug is fixed in 7.5.0 and I have kept the name zombie_pigman because of backwards compatibility. I want to be able to support old Minecraft-servers for a whiile... There are still people out there using MC 1.8.3 and 1.8.8 and MobHunting

**Comment by Rocologo** [comment]
Build 1057 countains support for RGB colors like you suggested {#RRGGBB} in the lang files the reward/head messages in config.yml

**Comment by Rocologo** [comment]
Im probably missing a message somewhere... just now I realize you cant use it in the reward-name itself. But no I have to go to the beach with my daughter so I will have to add this later.
