### ISSUE TITLE
Feature request: stacked BagOfGold heads reflect sum

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#664]
Spigot 1.16.1
MobHunting 7.5.1-SNAPSHOT-B1057

If it's possible: It would be nice if the display {value} of stacked BagOfGold heads (from killing multiple entities in location and time proximity) reflected the sum of the values. At present, the value of the first head is displayed, regardless of the number of stacked heads.

**Comment by Rocologo** [comment]
I think this will break the stacking - because Minecraft compare the Lores and display text when it decides if they can be stacked. 

I could do the manually then - but thinking about about how difficult it is to take care of all this, I dont think its a good idea. Im afraid that it will take a long time to make it stable. and I dont have much time to develop at the moment.

**Comment by SlimeDog** [comment]
No worries. It was just an idea. I can appreciate the difficulty. It's not worth the hassle. Thanks for reply.
