### ISSUE TITLE
Leaderboard: Ender Dragon Kills (All Time) has a typo

### ISSUE THREAD

**Issue by dfeneck** [Rocologo/MobHunting#736]
In the picture attached you can see the strange 'r' character next to the world Kills there. Probably just a typo in the code, happens to me all the time with my cat :)
![image](https://user-images.githubusercontent.com/78724526/159115531-4dca0fdf-7144-4210-8787-861965ff9d07.png)

**Comment by Rocologo** [comment]
This is actually not a "typo" it is because I try to break the name "Ender Dragon Kills" into to lines, trying to find the space, but the problem (bug) is that I didnt think about the colour codes. And I actually dont know how to solve the problem. ? 

in this case the "r" is actually "&r" .... hmm....

**Comment by Rocologo** [comment]
I think you can fix this problem on this sign in your lang file. Changing 

mobs.EnderDragon.name=§5Ender Dragon§r
to
mobs.EnderDragon.name=§5Ender Dragon

I also noticed that the color on line 3 is missing. I will see if I can fix that.

**Comment by Rocologo** [comment]
It works better now. 

file:////home/christian/.local/share/multimc/instances/1.18.2/.minecraft/screenshots/2022-04-17_18.10.08.png

**Comment by Rocologo** [comment]
![image](https://user-images.githubusercontent.com/1008133/163723008-49f6c2de-33d7-4217-9669-46b7cc3e15b7.png)
