### ISSUE TITLE
Not receiving reward when it's really low

### ISSUE THREAD

**Issue by zaxanq** [Rocologo/MobHunting#89]
Not sure if this was intended, but we wanted to make gaining emeralds not too easy, so I've made most of the mobs in the range 0.01 to 0.05 emeralds per kill and it works really fine, but I've made passive mobs with amounts like 0.003-0.009 and I just don't receive any reward. I've set reward rounding to 0.001:
reward_rounding: 0.001
but this doesn't help.

**Comment by Rocologo** [comment]
The original developer made a test somewhere in the plugin which set the minimum reward to 0.01. Non of us has imagined that could be a problem. I can change this in next version and 
Set minimum = rounding
Or minimum = 0.001 hardcoded like now
Or add minimum to config.yml

**Comment by Rocologo** [comment]
I think the last option is most flexible.

**Comment by Rocologo** [comment]
The test is added because of the grinding detection. If you kill a mob in the same area 10 times its okay, but after 10 times the reward is cut by 10% for each mob. This means that the reward will never be 0 so a minimum reward was set to 0.01. This worked fine until i started to integrate to Gringotts. 

Maybe the way you use gringotts / mobbunting introduces another problem. Today reward can only be a hole emerald and emerald_block. 

If Reward = 11.5, emerald_block = 9, emerald = 1
The reward is 1 emerald_block and 2 emeralds and the 0.5 is not dropped.

I am not if this is problem the way you want to use the emeralds. What is the values of your emeralds?

**Comment by zaxanq** [comment]
To be honest, If person gets 0.4 emeralds, then another 0.4 emeralds and another, it works fine, giving 1 emerald after third kill :) After some talk we decided it's not really that big of a deal if we set 0.003-0.008 or just simply 0.01. So whether you set lower minimum is up to you. :P Thanks for help anyway. :)

**Comment by Rocologo** [comment]
I have added the minimum setting in config.yml in Build 89

http://jenkins.lindegaard.one:8180/job/MobHunting/

About the Emeralds I cant drop 0.4 Emerald on the ground. ???? And I cant add the kills until you get 1 Emerald. Thats not really possible without to big changes.

**Comment by Rocologo** [comment]
You didnt tell mw what value you had given Emeralds and Emerald_Blocks?

**Comment by zaxanq** [comment]
if 1 = emeralds, if 9 = emerald_block
the amount for kill was 0.003:0.008 and rounding 0.001. I received nothing for kill. But today my friend said she received approx. 0.006 for an assist.

**Comment by zaxanq** [comment]
No no no, It's not like I get 0.4 emerald, and can drop it and stuff, but it's in the inventory balance somehow. And when it reaches 1 or over 1, I get an emerald (item).
Not sure how to explain it if you don't understand it so far. But I don't think I need to, my issue was about something different :P
